name: Unity Android Build

on:
  workflow_dispatch

jobs:
  unity-build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-Android-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-Android-library-

      - name: Extend Free Disk Space
        uses: jlumbroso/free-disk-space@main

      - name: Build Projects
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.20f1'
          targetPlatform: Android
          androidExportType: ${{ 'androidAppBundle' || '' }}
          androidKeystoreName: ${{ secrets.KEYSTORE_NAME }}
          androidKeystoreBase64: ${{ secrets.KEYSTORE_FILE }}
          androidKeystorePass: ${{ secrets.KEYSTORE_PASSWORD }}
          androidKeyaliasName: ${{  secrets.KEY_ALIAS }}
          androidKeyaliasPass: ${{  secrets.KEY_PASSWORD }}

      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: space.cosmicvoyagers
          releaseFiles: build/Android/Android.abb
          track: internal
