name: Unity Build

on:
  push:
    branches:
      - main

jobs:
  unity-build-linux:
    name: Build for ${{ matrix.targetPlatform }} in Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
          - PS4 # Build a PS4 standalone.
#          - PS5 # Build to PlayStation 5 platform.
          - XboxOne # Build an Xbox One standalone.
          - tvOS # Build a tvOS player.
          - Switch # Build a Nintendo Switch player.
#          - VisionOS # Build a visionOS player.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extend Free Disk Space
        if: >-
          matrix.targetPlatform == 'Android' ||
          matrix.targetPlatform == 'PS4' ||
          matrix.targetPlatform == 'XboxOne' ||
          matrix.targetPlatform == 'Switch'
        uses: jlumbroso/free-disk-space@main

      - name: Build
        uses: ./.github/actions/checkout-and-build
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: '2022.3.20f1'
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Create Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run: |
          mkdir deploy

      - name: Copy WebGL Build to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run: |
          cp -R build/WebGL/WebGL/* deploy/

      - name: Copy App Store Privacy Policy to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run : |
          mkdir deploy/AppStore
          cp AppleAppStorePrivacyPolicy.md deploy/AppStore/PrivacyPolicy.md

      - name: Copy Play Store Privacy Policy to Deploy Directory
        if: matrix.targetPlatform == 'WebGL'
        run : |
          mkdir deploy/PlayStore
          cp GooglePlayStorePrivacyPolicy.md deploy/PlayStore/PrivacyPolicy.md

      - name: Deploy to GitHub Pages
        if: matrix.targetPlatform == 'WebGL'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          keep_files: true
          enable_jekyll: true
          cname: www.cosmic-voyagers.space

  unity-build-windows:
    name: Build for ${{ matrix.targetPlatform }} in Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WSAPlayer # Build a Windows Store Apps player.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/checkout-and-build
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: '2022.3.20f1'
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          unityLicense: ${{ secrets.UNITY_LICENSE }}
